チャット画面の雛形の実装
umigit/chat-space pull request #2
Opened 2019-02-07 12:21 UTC by umi2019

# WHAT
チャットスペースのチャット画面を実装した。

# WHY
チャットをするため

2019-02-07 12:24 UTC, umi2019 commented
指示書: 
![chat-space](https://user-images.githubusercontent.com/45915489/52411273-8e6c8280-2b1e-11e9-8039-d4b0788d64b1.png)

自分が実装した画面:
<img width="1440" alt="chat-space_amanuma" src="https://user-images.githubusercontent.com/45915489/52411297-a512d980-2b1e-11e9-96a3-7eb34da019b8.png">

2019-02-07 12:30 UTC, yuki-uchida requested changes
こちら参考にしましょうhttps://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1

2019-02-07 12:30 UTC, yuki-uchida commented on app/assets/stylesheets/_sidebar.scss
> +.sidebar__header {
せっかくBEMに沿って記述していただいているので、アンバサンドを活用しましょう

2019-02-07 12:37 UTC, umi2019 commented on app/assets/stylesheets/_sidebar.scss
> +.sidebar__header {
ありがとうございます！
ネストした書き方できるんですね！

2019-02-08 03:19 UTC, umi2019 commented
CSSを&を使ってネストさせた記述に変更しました

合わせてHAMLのクラス名を調整しました

2019-02-08 03:23 UTC, miyagit commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ハッシュロケットを使わないようにしましょう。

2019-02-08 03:38 UTC, umigit reviewed
ハッシュロケットをシンボルに変更しました

2019-02-08 03:38 UTC, umi2019 commented on app/views/layouts/application.html.haml
> +    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
ありがとうございます！
古い書き方なんですね。

2019-02-08 03:49 UTC, miyagit commented on app/views/layouts/mailer.html.haml
> +!!!
mailer系のファイルは使わないので削除してもらって大丈夫です。

2019-02-08 04:03 UTC, umi2019 commented on app/views/layouts/mailer.html.haml
> +!!!
ありがとうございます！
自動生成系のファイルでも結構修正が必要なんですね。。。

2019-02-08 04:04 UTC, umigit reviewed
mailerに関するファイルを削除しました

2019-02-08 04:50 UTC, hirozak commented on app/assets/stylesheets/_sidebar.scss
> +$header_height: 100px;
変数はapplication.scssで読み込みましょう

2019-02-08 04:50 UTC, hirozak commented on app/assets/stylesheets/application.scss
> +$footer_height: 90px;
変数のファイル作りましょう

2019-02-08 04:50 UTC, hirozak commented on app/assets/stylesheets/application.scss
> +  flex-direction: column;
別ファイルでスタイルは書きましょう。このファイルは読み込みだけにしてください

2019-02-08 04:55 UTC, umi2019 commented on app/assets/stylesheets/application.scss
> +  flex-direction: column;
なるほど！
分割の仕方勉強になります！

2019-02-08 07:23 UTC, umigit reviewed
CSSを分割化しました

それに伴いクラス名も調整しました

2019-02-08 07:29 UTC, kuroko918 reviewed
一点確認お願いします。

2019-02-08 07:29 UTC, kuroko918 commented on app/assets/stylesheets/_contents.scss
> +// }
こちらのコメントアウトしてある記述は使用しますでしょうか？

2019-02-08 07:31 UTC, umi2019 commented on app/assets/stylesheets/_contents.scss
> +// }
使用しません！
消し忘れです！

2019-02-08 07:38 UTC, umigit reviewed
不要なコメントを削除しました

2019-02-08 07:41 UTC, yuki-uchida commented
LGTMです！お疲れ様でした

2019-02-08 07:42 UTC, umi2019 commented
ありがとうございます！！

2019-02-08 07:42 UTC, merged